<?php
/** @var $block Esgi\Beer\Block\Beer */
$beers = $block->getBeers();
?>
<ul id="beer-list">
    <?php foreach ($beers as $beer) : ?>
        <li><?php echo $beer->getTitle(); ?></li>
    <?php endforeach; ?>
</ul>
<field name="beer_id" formElement="select" sortOrder="10">
    <settings>
        <dataType>text</dataType>
        <label translate="true">Beer</label>
        <validation>
            <rule name="required-entry" xsi:type="boolean">true</rule>
        </validation>
    </settings>
    <formElements>
        <select>
            <settings>
                <options class="Esgi\Beer\Model\Config\Source\Beer"/>
            </settings>
        </select>
    </formElements>
</field>
