<?php
/** @var $block Esgi\Beer\Block\View */
$beer = $block->getBeer();
?>

<div>coucou</div>
<?php

echo '<pre style="font-size: 10px;"><code>';
print_r($beer);
echo '</code></pre>';

?>
<!--
<field name="beer_id" formElement="select" sortOrder="10">
    <settings>
        <dataType>text</dataType>
        <label translate="true">Beer</label>
        <validation>
            <rule name="required-entry" xsi:type="boolean">true</rule>
        </validation>
    </settings>
    <formElements>
        <select>
            <settings>
                <options class="Esgi\Beer\Model\Config\Source\Beer"/>
            </settings>
        </select>
    </formElements>
</field>
-->
