<?php
/** @var $block Esgi\Beer\Block\Brewery */
$departments = $block->getDepartments();
?>
<ul id="department-list">
    <?php foreach ($departments as $department) : ?>
        <li><?php echo $department->getTitle(); ?></li>
    <?php endforeach; ?>
</ul>
<field name="brewery_id" formElement="select" sortOrder="10">
    <settings>
        <dataType>text</dataType>
        <label translate="true">Brewery</label>
        <validation>
            <rule name="required-entry" xsi:type="boolean">true</rule>
        </validation>
    </settings>
    <formElements>
        <select>
            <settings>
                <options class="Esgi\Beer\Model\Config\Source\Brewery"/>
            </settings>
        </select>
    </formElements>
</field>
